### ISSUE TITLE
More docs?

### ISSUE THREAD

**Issue by kirjs** [benjamn/ast-path#2]
I would like to learn more about the tool and try it, but I don't even know where to strat.

**Comment by benjamn** [comment]
Hi @kcherkashin, thanks for asking. Documentation is lacking for sure, but one thing I should mention that this repository has actually become part of https://github.com/benjamn/ast-types (see https://github.com/benjamn/ast-types/blob/master/lib/path.js), and there's a brief example of traversing an AST in [the README.md file](https://github.com/benjamn/ast-types#ast-traversal) for that repository. Hope that helps a little!
